[package]
name = "glio"
version = "0.0.1"
edition = "2021"
authors = ["Dmitriy Mayorov<MayorDi@yandex.ru>"]
license = "Apache-2.0"
keywords = ["OpenGL", "GL"]
categories = ["graphics"]
readme = "README.md"
homepage = ""
repository = ""

[dependencies]
gl = "0.14.0"